<?php
$title = 'Supprimer un client';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sûr de vouloir supprimer le client 
    '<?php echo $this->escapeHtml($client->first_name); ?>
    <?php echo $this->escapeHtml($client->last_name); ?>'?
</p>
<?php
$url = $this->url('client', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $client->id; ?>" />
    <input type="submit" name="del" value="Oui" />
    <input type="submit" name="del" value="Non" />
</div>
</form>