<?php
$title = 'Clients';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('client', array('action'=>'add'));?>">Add new client</a>
</p>

<table class="table">
<tr>
    <th>Prénom</th>
    <th>Nom</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($clients as $client) : ?>
<tr>
    <td><?php echo $this->escapeHtml($client->first_name);?></td>
    <td><?php echo $this->escapeHtml($client->last_name);?></td>
    <td>
        <a href="<?php echo $this->url('client',
            array('action'=>'edit', 'id' => $client->id));?>">Edit</a>
        <a href="<?php echo $this->url('client',
            array('action'=>'delete', 'id' => $client->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>