<?php
$title = 'Ajouter un bon';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('application/default', array('controller'=> 'bon', 'action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('id_expediteur'));
echo $this->formRow($form->get('number'));
echo $this->formRow($form->get('date'));
echo $this->formRow($form->get('mode'));
echo $this->formRow($form->get('destinataire_name'));
echo $this->formRow($form->get('destinataire_adress1'));
echo $this->formRow($form->get('destinataire_adress2'));
echo $this->formRow($form->get('destinataire_zipcode'));
echo $this->formRow($form->get('destinataire_city'));
echo $this->formRow($form->get('destinataire_country'));
echo $this->formRow($form->get('destinataire_phone'));
echo $this->formRow($form->get('ligne1_quantity'));
echo $this->formRow($form->get('ligne1_label'));
echo $this->formRow($form->get('ligne1_size'));
echo $this->formRow($form->get('ligne1_price'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();