<?php
$title = 'Supprimer un bon';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sûr de vouloir supprimer le bon 
    '<?php echo $this->escapeHtml($bon->number); ?>' ?
</p>
<?php
$url = $this->url('application/default', array(
	'controller'=> 'bon',
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $bon->id; ?>" />
    <input type="submit" name="del" value="Oui" />
    <input type="submit" name="del" value="Non" />
</div>
</form>