<?php echo $this->doctype(); ?>
<!--[if IE 8]>    <html class="no-js ie8 ie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9 ie" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/wuxia-blue.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->prependFile($this->basePath() . '/js/bootstrap/bootstrap.js')
                                  ->prependFile($this->basePath() . '/js/navigation.js')
                                  ->prependFile($this->basePath() . '/js/libs/modernizr.js')
                                  ->prependFile($this->basePath() . '/js/libs/modernizr.js') 
                                  ->prependFile($this->basePath() . '/js/libs/jquery.js')?>
    <script>
    $(document).ready(function(){

                // Navbar tooltips
                $('.navbar [title]').tooltip({
                    placement: 'bottom'
                });
                
                // Content tooltips
                $('[role=main] [title]').tooltip({
                    placement: 'top'
                });
                
                // Dropdowns
                $('.dropdown-toggle').dropdown();
                
            });
    </script>
</head>

<body>
    <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">

                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span class="awe-user"></span></button>
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"><span class="awe-chevron-down"></span></button>

                <a class="brand" href="/">Global Bon</a>

                <div class="nav-collapse">

                    <!-- Main navigation -->
                    <nav class="navigation">
                        <ul class="nav active-arrows" role="navigation">
                            <li class="active">
                                <a href="/">
                                    <span class="awe-home"></span>
                                    Accueil
                                </a>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->url('application/default', array('controller' => 'bon')); ?>">
                                    <div><span class="awe-book"></span> Gestion des Bons</div>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="<?php echo $this->url('application/default', array('controller' => 'bon')); ?>"><span class="awe-list"></span> Liste des bons</a></li>
                                    <li><a href="<?php echo $this->url('application/default', array('controller' => 'bon', 'action' => 'add')); ?>"><span class="awe-pencil"></span> Ajouter un bon</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="<?php echo $this->url('application/default', array('controller' => 'expediteur')); ?>">
                                    <div><span class="awe-user"></span> Expediteurs</div>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="<?php echo $this->url('application/default', array('controller' => 'expediteur')); ?>"><span class="awe-list"></span> Liste des expediteurs</a></li>
                                    <li><a href="<?php echo $this->url('application/default', array('controller' => 'expediteur', 'action' => 'add')); ?>"><span class="awe-pencil"></span> Ajouter un expediteur</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>

                    <!-- User navigation -->
                    <nav class="user">
                        <div class="user-info pull-right">
                            <img src="http://placekitten.com/35/35" alt="User avatar">
                            <div class="btn-group">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                    <div><strong>John Pixel</strong>Administrateur</div>
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href=""><span class="awe-cogs"></span> Préférences</a></li>
                                    <li><a href="<?php echo $this->url('application/default', array('controller' => 'user')); ?>"><span class="awe-group"></span> Gestion des utilisteurs</a></li>
                                    <li class="divider"></li>
                                    <li><a href="<?php echo $this->url('zfcuser/logout'); ?>"><span class="awe-signout"></span> Déconnexion</a></li>
                                </ul>
                            </div>
                        </div>
                    </nav>

                </div>
            </div>
        </div>
    </header>
    <!-- /Main navigation bar -->

    <!-- Main content -->
    <div class="container" role="main">

        <!-- Breadcrumbs -->
        <ul class="breadcrumb">
            <li><a href="#"><span class="awe-home"></span> Accueil</a></li>
            <li class="active">Page en cours</li>
        </ul>
        <!-- Breadcrumbs -->

        <!-- Main data container -->
        <div class="content">
            <?php echo $this->content; ?>
        </div>

    </div>
    <!-- /Main content -->

    <!-- Main footer -->
    <footer class="container">
        <nav>
            <ul>
                <li>&copy; 2013. All rights reserved.</li>
            </ul>
        </nav>
    </footer>
    <!-- /Main footer -->

    <?php echo $this->inlineScript() ?>
</body>

</html>
