<?php
$title = 'Expediteurs';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('application/default', array('controller'=> 'expediteur', 'action'=>'add'));?>">Ajouter un expediteur</a>
</p>

<table class="table">
<tr>
    <th>Nom</th>
    <th>Code Postal</th>
    <th>Ville</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($expediteurs as $expediteur) : ?>
<tr>
    <td><?php echo $this->escapeHtml($expediteur->name);?></td>
    <td><?php echo $this->escapeHtml($expediteur->zipcode);?></td>
    <td><?php echo $this->escapeHtml($expediteur->country);?></td>
    <td>
        <a href="<?php echo $this->url('application/default',
            array('controller'=> 'expediteur', 'action'=>'edit', 'id' => $expediteur->id));?>">Edit</a>
        <a href="<?php echo $this->url('application/default',
            array('controller'=> 'expediteur', 'action'=>'delete', 'id' => $expediteur->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>