<?php
$title = 'Supprimer un utilisateur';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Êtes-vous sûr de vouloir supprimer l'utilisateur
    '<?php echo $this->escapeHtml($user->username); ?>
    <?php echo $this->escapeHtml($user->email); ?>'?
</p>
<?php
$url = $this->url('application/default', array(
	'controller'=> 'user',
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $user->id; ?>" />
    <input type="submit" name="del" value="Oui" />
    <input type="submit" name="del" value="Non" />
</div>
</form>